version: "3"
services:
  app:
    build:
      context: .
    container_name: pryv-to-thryve
    restart: on-failure
    user: node
    networks:
      - app
    ports:
      - "2606:2606"
    tty: true
    volumes:
      - ./:/app

networks:
  app:
