module.exports = {
	1: 'Fitbit',
	2: 'Garmin',
	3: 'Polar',
	5: 'Apple',
	6: 'Samsung',
	7: 'Misfit',
	8: 'Withings',
	9: 'Thryve Connector',
	10: 'Thryve Wearable Connector',
	11: 'Strava',
	12: 'GoogleFit REST',
	13: 'Xiaomi',
	14: 'MyFitnessPal',
	15: 'Runtastic',
	16: 'Omron',
	17: 'Suunto',
	18: 'Oura',
	19: 'Runkeeper',
	20: 'Endomondo',
	21: 'iHealth',
	22: 'Abbott(FreeStyleLibre)',
	23: 'Medisana',
	24: 'Sleep As Android',
	25: 'Clue',
	26: 'HealthForYou',
	27: 'Beurer',
	30: 'Lykon',
	31: 'Lifesum',
	32: 'Ovy',
	1000: 'Multiple'
};
